apiVersion: tensorflow.org/v1alpha1
kind: TfJob
metadata:
  name: distributed-mnist
spec:
  tensorboard:
    logDir: /tmp/tensorflow/logs
    serviceType: LoadBalancer
    volumes:
      - name: azurefile
        azureFile:
            secretName: azure-secret
            shareName: tensorflow3
    volumeMounts:
      - mountPath: /tmp/tensorflow 
        name: azurefile
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          volumes:
            - name: azurefile
              azureFile:
                  secretName: azure-secret
                  shareName: tensorflow3
                  readOnly: false
          containers:
            - image: wbuchwalter/dist-mnist             
              name: tensorflow
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /tmp/tensorflow
                  name: azurefile
          restartPolicy: OnFailure
    - replicas: 2
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: wbuchwalter/dist-mnist              
              name: tensorflow
              imagePullPolicy: Always
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: PS