apiVersion: tensorflow.org/v1alpha1
kind: TfJob
metadata:
  name: example-tfjob
spec:
  replicaSpecs:
    - template:
        spec:
          containers:
            - image: wbuchwalter/tensorflow-for-poets:cpu
              name: tensorflow
              volumeMounts:
                - name: azurefile
                  mountPath: /app/tf_files
          volumes:
            - name: azurefile
              azureFile:
                secretName: azure-secret
                shareName: tensorflow
                readOnly: false
          restartPolicy: OnFailure